# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Thu Apr 13 22:35:39 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(921, 622)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.matplot_buttons_hlayout = QtGui.QHBoxLayout()
        self.matplot_buttons_hlayout.setObjectName(_fromUtf8("matplot_buttons_hlayout"))
        self.matplot_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplot_widget.sizePolicy().hasHeightForWidth())
        self.matplot_widget.setSizePolicy(sizePolicy)
        self.matplot_widget.setObjectName(_fromUtf8("matplot_widget"))
        self.matplot_vlayout = QtGui.QVBoxLayout(self.matplot_widget)
        self.matplot_vlayout.setMargin(0)
        self.matplot_vlayout.setObjectName(_fromUtf8("matplot_vlayout"))
        self.matplot_buttons_hlayout.addWidget(self.matplot_widget)
        self.ch1_vlayout = QtGui.QVBoxLayout()
        self.ch1_vlayout.setObjectName(_fromUtf8("ch1_vlayout"))
        self.ch1_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.ch1_checkbox.setObjectName(_fromUtf8("ch1_checkbox"))
        self.ch1_vlayout.addWidget(self.ch1_checkbox)
        self.ch1_coupling_combo = QtGui.QComboBox(self.centralwidget)
        self.ch1_coupling_combo.setObjectName(_fromUtf8("ch1_coupling_combo"))
        self.ch1_coupling_combo.addItem(_fromUtf8(""))
        self.ch1_coupling_combo.addItem(_fromUtf8(""))
        self.ch1_coupling_combo.addItem(_fromUtf8(""))
        self.ch1_vlayout.addWidget(self.ch1_coupling_combo)
        self.ch1_measure_label = QtGui.QLabel(self.centralwidget)
        self.ch1_measure_label.setObjectName(_fromUtf8("ch1_measure_label"))
        self.ch1_vlayout.addWidget(self.ch1_measure_label)
        self.ch1_measure_textedit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1_measure_textedit.sizePolicy().hasHeightForWidth())
        self.ch1_measure_textedit.setSizePolicy(sizePolicy)
        self.ch1_measure_textedit.setMinimumSize(QtCore.QSize(150, 250))
        self.ch1_measure_textedit.setMaximumSize(QtCore.QSize(150, 5000))
        self.ch1_measure_textedit.setReadOnly(True)
        self.ch1_measure_textedit.setObjectName(_fromUtf8("ch1_measure_textedit"))
        self.ch1_vlayout.addWidget(self.ch1_measure_textedit)
        self.ch1_lpfilter_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.ch1_lpfilter_checkbox.setObjectName(_fromUtf8("ch1_lpfilter_checkbox"))
        self.ch1_vlayout.addWidget(self.ch1_lpfilter_checkbox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ch1_vlayout.addItem(spacerItem)
        self.matplot_buttons_hlayout.addLayout(self.ch1_vlayout)
        self.channels_vline = QtGui.QFrame(self.centralwidget)
        self.channels_vline.setFrameShape(QtGui.QFrame.VLine)
        self.channels_vline.setFrameShadow(QtGui.QFrame.Sunken)
        self.channels_vline.setObjectName(_fromUtf8("channels_vline"))
        self.matplot_buttons_hlayout.addWidget(self.channels_vline)
        self.ch2_vlayout = QtGui.QVBoxLayout()
        self.ch2_vlayout.setObjectName(_fromUtf8("ch2_vlayout"))
        self.ch2_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.ch2_checkbox.setObjectName(_fromUtf8("ch2_checkbox"))
        self.ch2_vlayout.addWidget(self.ch2_checkbox)
        self.ch2_coupling_combo = QtGui.QComboBox(self.centralwidget)
        self.ch2_coupling_combo.setObjectName(_fromUtf8("ch2_coupling_combo"))
        self.ch2_coupling_combo.addItem(_fromUtf8(""))
        self.ch2_coupling_combo.addItem(_fromUtf8(""))
        self.ch2_coupling_combo.addItem(_fromUtf8(""))
        self.ch2_vlayout.addWidget(self.ch2_coupling_combo)
        self.ch2_measure_label = QtGui.QLabel(self.centralwidget)
        self.ch2_measure_label.setObjectName(_fromUtf8("ch2_measure_label"))
        self.ch2_vlayout.addWidget(self.ch2_measure_label)
        self.ch2_measure_textedit = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2_measure_textedit.sizePolicy().hasHeightForWidth())
        self.ch2_measure_textedit.setSizePolicy(sizePolicy)
        self.ch2_measure_textedit.setMinimumSize(QtCore.QSize(150, 250))
        self.ch2_measure_textedit.setMaximumSize(QtCore.QSize(150, 250))
        self.ch2_measure_textedit.setReadOnly(True)
        self.ch2_measure_textedit.setObjectName(_fromUtf8("ch2_measure_textedit"))
        self.ch2_vlayout.addWidget(self.ch2_measure_textedit)
        self.ch2_lpfilter_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.ch2_lpfilter_checkbox.setObjectName(_fromUtf8("ch2_lpfilter_checkbox"))
        self.ch2_vlayout.addWidget(self.ch2_lpfilter_checkbox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.ch2_vlayout.addItem(spacerItem1)
        self.matplot_buttons_hlayout.addLayout(self.ch2_vlayout)
        self.verticalLayout.addLayout(self.matplot_buttons_hlayout)
        self.hline = QtGui.QFrame(self.centralwidget)
        self.hline.setFrameShape(QtGui.QFrame.HLine)
        self.hline.setFrameShadow(QtGui.QFrame.Sunken)
        self.hline.setObjectName(_fromUtf8("hline"))
        self.verticalLayout.addWidget(self.hline)
        self.cmd_query_hlayout = QtGui.QHBoxLayout()
        self.cmd_query_hlayout.setObjectName(_fromUtf8("cmd_query_hlayout"))
        self.serial_combo = QtGui.QComboBox(self.centralwidget)
        self.serial_combo.setObjectName(_fromUtf8("serial_combo"))
        self.cmd_query_hlayout.addWidget(self.serial_combo)
        self.autoset_button = QtGui.QPushButton(self.centralwidget)
        self.autoset_button.setObjectName(_fromUtf8("autoset_button"))
        self.cmd_query_hlayout.addWidget(self.autoset_button)
        self.acquire_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acquire_button.sizePolicy().hasHeightForWidth())
        self.acquire_button.setSizePolicy(sizePolicy)
        self.acquire_button.setObjectName(_fromUtf8("acquire_button"))
        self.cmd_query_hlayout.addWidget(self.acquire_button)
        self.fft_button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fft_button.sizePolicy().hasHeightForWidth())
        self.fft_button.setSizePolicy(sizePolicy)
        self.fft_button.setObjectName(_fromUtf8("fft_button"))
        self.cmd_query_hlayout.addWidget(self.fft_button)
        self.longmem_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.longmem_checkbox.setObjectName(_fromUtf8("longmem_checkbox"))
        self.cmd_query_hlayout.addWidget(self.longmem_checkbox)
        self.persist_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.persist_checkbox.setObjectName(_fromUtf8("persist_checkbox"))
        self.cmd_query_hlayout.addWidget(self.persist_checkbox)
        self.equiv_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.equiv_checkbox.setObjectName(_fromUtf8("equiv_checkbox"))
        self.cmd_query_hlayout.addWidget(self.equiv_checkbox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.cmd_query_hlayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.cmd_query_hlayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.acquire_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.Acquire)
        QtCore.QObject.connect(self.fft_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.calculateFFT)
        QtCore.QObject.connect(self.autoset_button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.aset)
        QtCore.QObject.connect(self.ch1_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.ch_toggled)
        QtCore.QObject.connect(self.ch2_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.ch_toggled)
        QtCore.QObject.connect(self.ch1_coupling_combo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.ch_coupling_changed)
        QtCore.QObject.connect(self.ch2_coupling_combo, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.ch_coupling_changed)
        QtCore.QObject.connect(self.persist_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.persist_toggled)
        QtCore.QObject.connect(self.equiv_checkbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), MainWindow.equiv_toggled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "IWATSU Digital Oscilloscope DS-8812 BRINGO", None))
        self.ch1_checkbox.setText(_translate("MainWindow", "Channel 1", None))
        self.ch1_coupling_combo.setItemText(0, _translate("MainWindow", "AC", None))
        self.ch1_coupling_combo.setItemText(1, _translate("MainWindow", "DC", None))
        self.ch1_coupling_combo.setItemText(2, _translate("MainWindow", "GND", None))
        self.ch1_measure_label.setText(_translate("MainWindow", "Measurements", None))
        self.ch1_lpfilter_checkbox.setText(_translate("MainWindow", "Low-pass filter", None))
        self.ch2_checkbox.setText(_translate("MainWindow", "Channel 2", None))
        self.ch2_coupling_combo.setItemText(0, _translate("MainWindow", "AC", None))
        self.ch2_coupling_combo.setItemText(1, _translate("MainWindow", "DC", None))
        self.ch2_coupling_combo.setItemText(2, _translate("MainWindow", "GND", None))
        self.ch2_measure_label.setText(_translate("MainWindow", "Measurements", None))
        self.ch2_lpfilter_checkbox.setText(_translate("MainWindow", "Low-pass filter", None))
        self.autoset_button.setText(_translate("MainWindow", "Autoset", None))
        self.acquire_button.setText(_translate("MainWindow", "Acquire", None))
        self.fft_button.setText(_translate("MainWindow", "FFT", None))
        self.longmem_checkbox.setText(_translate("MainWindow", "Long memory", None))
        self.persist_checkbox.setText(_translate("MainWindow", "Persistence", None))
        self.equiv_checkbox.setText(_translate("MainWindow", "Equiv. sampling", None))

